"""Gmail Pusher - sends analysis reports via Gmail."""

import html
import smtplib
import ssl
import os
import time
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dataclasses import dataclass
from typing import Optional


def _escape_html(text):
    """Escape HTML characters to prevent injection."""
    if isinstance(text, str):
        return html.escape(text)
    return str(text)


def _fmt_price(price):
    """Format price for display in email."""
    return f"${price:.2f}"


def _fmt_pnl(pnl):
    """Format P/L for display in email."""
    return f"${pnl:.2f}"


@dataclass
class EmailMessage:
    """Email message structure."""
    subject: str
    body: str
    to_email: str
    cc_email: Optional[str] = None


class GmailPusher:
    """Sends emails via Gmail SMTP."""

    def __init__(self, sender_email: str, recipient_email: str,
                 smtp_host: str = "smtp.gmail.com",
                 smtp_port: int = 465):
        self.sender_email = sender_email
        self.recipient_email = recipient_email
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port

    def _get_credentials(self) -> tuple[str, str]:
        """Get SMTP credentials from environment."""
        email_user = os.getenv("GMAIL_EMAIL")
        email_pass = os.getenv("GMAIL_APP_PASSWORD")
        if not email_user or not email_pass:
            raise ValueError(
                "Gmail credentials not set. Please set GMAIL_EMAIL and GMAIL_APP_PASSWORD environment variables."
            )
        return email_user, email_pass

    def send_email(self, message: EmailMessage) -> bool:
        """Send an email via Gmail SMTP over SSL (port 465)."""
        try:
            email_user, email_pass = self._get_credentials()

            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = message.to_email
            if message.cc_email:
                msg['Cc'] = message.cc_email
            msg['Subject'] = message.subject

            msg.attach(MIMEText(message.body, 'html'))

            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(self.smtp_host, self.smtp_port, context=context) as server:
                server.login(email_user, email_pass)
                server.send_message(msg)

            return True
        except smtplib.SMTPException as e:
            print(f"Failed to send email: {e}")
            return False

    def send_with_retry(self, message: EmailMessage, max_retries: int = 3) -> bool:
        """Send email with retry logic."""
        delays = [5, 15, 60]  # minutes
        for attempt in range(max_retries):
            if self.send_email(message):
                return True
            if attempt < max_retries - 1:
                wait_time = delays[attempt] * 60
                print(f"Retry {attempt + 1}/{max_retries} in {delays[attempt]} minutes...")
                time.sleep(wait_time)
        return False

    def format_premarket_briefing(self, report: dict) -> EmailMessage:
        """Format premarket briefing email."""
        positions = report.get("positions", [])
        sentiment = report.get("sentiment", "neutral")
        events = report.get("events", [])

        # Build table rows
        rows = []
        for p in positions:
            ticker = _escape_html(p['ticker'])
            shares = _escape_html(str(p['shares']))
            price = _escape_html(_fmt_price(p['entry_price']))
            rows.append(f"<tr><td>{ticker}</td><td>{shares}</td><td>{price}</td></tr>")

        body = f"""
        <h2>Pre-market Briefing</h2>
        <h3>Portfolio Positions</h3>
        <table border="1" cellpadding="5" cellspacing="0">
            <tr><th>Ticker</th><th>Shares</th><th>Entry Price</th></tr>
            {''.join(rows)}
        </table>

        <h3>Market Sentiment</h3>
        <p>{_escape_html(sentiment.upper())}</p>

        <h3>Key Events Today</h3>
        <ul>
            {''.join(f"<li>{_escape_html(e)}</li>" for e in events)}
        </ul>

        <p><em>Generated by TradingAgents</em></p>
        """

        return EmailMessage(
            subject=f"Pre-market Briefing - {_escape_html(report.get('date', 'Today'))}",
            body=body,
            to_email=self.recipient_email
        )

    def format_afterhours_report(self, report: dict) -> EmailMessage:
        """Format after-hours report email."""
        positions = report.get("positions", [])
        analysis = report.get("analysis", "")

        # Build table rows
        rows = []
        for p in positions:
            ticker = _escape_html(p['ticker'])
            shares = _escape_html(str(p['shares']))
            current = _escape_html(p.get('current_price', 'N/A'))
            action = _escape_html(p.get('action', 'Hold'))
            rows.append(f"<tr><td>{ticker}</td><td>{shares}</td><td>{current}</td><td>{action}</td></tr>")

        body = f"""
        <h2>After-hours Report</h2>
        <h3>Portfolio Performance</h3>
        <table border="1" cellpadding="5" cellspacing="0">
            <tr><th>Ticker</th><th>Shares</th><th>Current/Pivot</th><th>Action</th></tr>
            {''.join(rows)}
        </table>

        <h3>Analysis Summary</h3>
        <p>{_escape_html(analysis)}</p>

        <p><em>Generated by TradingAgents</em></p>
        """

        return EmailMessage(
            subject=f"After-hours Report - {_escape_html(report.get('date', 'Today'))}",
            body=body,
            to_email=self.recipient_email
        )

    def format_screener_report(self, report: dict) -> "EmailMessage":
        """Format full stock screener + portfolio rebalancer report as HTML email."""
        scan_date = report.get("scan_date", "")
        sectors = report.get("sector_rankings", [])
        all_stocks = report.get("all_stocks", [])
        top_by_sector = report.get("top_by_sector", {})
        adjustments = report.get("adjustments", [])
        unchanged = report.get("unchanged", [])
        anomalies = report.get("anomalies", [])
        positions = report.get("portfolio_positions", [])

        # --- Anomaly alerts (top of report) ---
        anomaly_section = ""
        if anomalies:
            anomaly_rows = ""
            for a in anomalies:
                severity_color = {"high": "red", "medium": "orange", "low": "gray"}.get(a.get("severity", "medium"), "gray")
                anomaly_rows += f"""
                <tr style="color:{severity_color}">
                  <td><strong>{html.escape(a['sector'])}</strong></td>
                  <td><strong>{html.escape(a['signal'])}</strong></td>
                  <td>{html.escape(a.get('description', ''))}</td>
                  <td>{html.escape(a.get('data_source', ''))}</td>
                  <td>{html.escape(a.get('severity', 'medium').upper())}</td>
                </tr>"""
            anomaly_section = f"""
    <div style="border:2px solid red;padding:10px;margin:10px 0;border-radius:5px">
    <h2 style="color:red;margin-top:0">⚠️ 异动板块提醒</h2>
    <table border='1' cellpadding='5' cellspacing='0'>
      <tr><th>板块</th><th>信号类型</th><th>描述</th><th>数据来源</th><th>严重程度</th></tr>
      {anomaly_rows}
    </table>
    </div>"""

        # --- Sector table ---
        sector_rows = ""
        for s in sectors:
            b = s.get("breakdown", {})
            sector_rows += f"""
        <tr>
          <td>{s['rank']}</td>
          <td><strong>{html.escape(s['name'])}</strong></td>
          <td><strong>{s['score']:.3f}</strong></td>
          <td>{b.get('momentum', '-'):.3f}</td>
          <td>{b.get('valuation', '-'):.3f}</td>
          <td>{b.get('macro', '-'):.3f}</td>
          <td>{b.get('fundamentals', '-'):.3f}</td>
        </tr>"""
        sectors_table = f"""
    <h2>一、板块扫描结果</h2>
    <p>权重方法: A(动量)×0.4 + B(估值)×0.3 + E(宏观)×0.2 + C(基本面)×0.1</p>
    <table border='1' cellpadding='5' cellspacing='0'>
      <tr><th>排名</th><th>板块</th><th>综合得分</th><th>动量(A)</th><th>估值(B)</th><th>宏观(E)</th><th>基本面(C)</th></tr>
      {sector_rows}
    </table>"""

        # --- Individual stock recommendations (top 3 per sector) ---
        stock_rows = ""
        for sector_name, stocks in top_by_sector.items():
            for stock_data in stocks:
                scores = stock_data.get("scores", {})
                stock_rows += f"""
        <tr>
          <td><strong>{html.escape(stock_data.get('stock', ''))}</strong></td>
          <td>{html.escape(sector_name)}</td>
          <td><strong>{stock_data.get('composite', 0):.3f}</strong></td>
          <td>{scores.get('momentum', '-')}</td>
          <td>{scores.get('valuation', '-')}</td>
          <td>{scores.get('macro', '-')}</td>
          <td>{scores.get('fundamentals', '-')}</td>
          <td>{html.escape(stock_data.get('rating', ''))}</td>
        </tr>"""
        stocks_table = f"""
    <h2>二、个股推荐（每板块 Top 3）</h2>
    <table border='1' cellpadding='5' cellspacing='0'>
      <tr><th>股票</th><th>板块</th><th>综合得分</th><th>动量</th><th>估值</th><th>宏观</th><th>基本面</th><th>评级</th></tr>
      {stock_rows}
    </table>"""

        # --- Portfolio positions ---
        pos_section = ""
        if positions:
            pos_rows = ""
            total_value = 0
            for p in positions:
                value = p.get("shares", 0) * p.get("entry_price", 0)
                total_value += value
                pos_rows += f"""
        <tr>
          <td>{html.escape(p.get('ticker', ''))}</td>
          <td>{p.get('shares', 0)}</td>
          <td>${p.get('entry_price', 0):.2f}</td>
          <td>${value:.2f}</td>
          <td>{html.escape(p.get('broker', ''))}</td>
        </tr>"""
            pos_section = f"""
    <h2>三、现有持仓</h2>
    <p>总持仓市值: <strong>${total_value:.2f}</strong></p>
    <table border='1' cellpadding='5' cellspacing='0'>
      <tr><th>股票</th><th>股数</th><th>买入价</th><th>市值</th><th>券商</th></tr>
      {pos_rows}
    </table>"""

        # --- Adjustments ---
        reduce_rows = "".join(
            f"<tr><td>{html.escape(a['ticker'])}</td><td>{a['current_shares']}</td><td>减至{a['recommended_shares']}股</td><td>{html.escape(a.get('reason', ''))}</td></tr>"
            for a in adjustments if a["action"] in ("REDUCE", "ADD")
        )
        new_rows = "".join(
            f"<tr><td>{html.escape(a['ticker'])}</td><td>建议新建仓{a['recommended_shares']}股</td><td>{html.escape(a.get('reason', ''))}</td></tr>"
            for a in adjustments if a["action"] == "NEW"
        )
        hold_rows = "".join(
            f"<tr><td>{html.escape(u['ticker'])}</td><td>{html.escape(u.get('reason', ''))}</td></tr>"
            for u in unchanged
        )
        adjustments_section = f"""
    <h2>四、持仓调整建议</h2>
    {('<h3>建议减仓</h3><table border="1" cellpadding="5" cellspacing="0"><tr><th>股票</th><th>当前持仓</th><th>建议</th><th>原因</th></tr>' + reduce_rows + '</table>' if reduce_rows else '<p>无减仓建议</p>')}
    {('<h3>新建仓机会</h3><table border="1" cellpadding="5" cellspacing="0"><tr><th>股票</th><th>建议</th><th>原因</th></tr>' + new_rows + '</table>' if new_rows else '')}
    {('<h3>持仓不变</h3><table border="1" cellpadding="5" cellspacing="0"><tr><th>股票</th><th>原因</th></tr>' + hold_rows + '</table>' if hold_rows else '')}"""

        body = f"""
    <div style="font-family:Arial,sans-serif;max-width:900px">
    <h1 style="color:#333">Daily Stock Screener & Portfolio Rebalancer</h1>
    <p><em>扫描日期: {scan_date} | 报告生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M')}</em></p>
    {anomaly_section}
    {sectors_table}
    {stocks_table}
    {pos_section}
    {adjustments_section}
    <p style="margin-top:20px"><em>Generated by TradingAgents Stock Screener | 权重: A×0.4 + B×0.3 + E×0.2 + C×0.1</em></p>
    </div>
    """
        return EmailMessage(
            subject=f"[TradingAgents] Stock Screener Report — {scan_date}",
            body=body,
            to_email=self.recipient_email,
        )

    def format_deep_screener_report(self, report: dict) -> "EmailMessage":
        """Full report with per-stock TradingAgents analysis + decision layers."""
        scan_date = report.get("scan_date", "")
        deep_stocks = report.get("deep_stocks", [])
        sector_rankings = report.get("sector_rankings", [])
        anomalies = report.get("anomalies", [])
        portfolio_positions = report.get("portfolio_positions", [])
        adjustments = report.get("adjustments", [])
        unchanged = report.get("unchanged", [])

        # --- Anomaly alerts ---
        anomaly_section = ""
        if anomalies:
            anomaly_rows = ""
            for a in anomalies:
                severity_color = {"high": "red", "medium": "orange", "low": "gray"}.get(
                    a.get("severity", "medium"), "gray"
                )
                anomaly_rows += f"""
                <tr style="color:{severity_color}">
                  <td><strong>{html.escape(a.get('sector', ''))}</strong></td>
                  <td><strong>{html.escape(a.get('signal', ''))}</strong></td>
                  <td>{html.escape(a.get('description', ''))}</td>
                  <td>{html.escape(a.get('data_source', ''))}</td>
                  <td>{html.escape(a.get('severity', 'medium').upper())}</td>
                </tr>"""
            anomaly_section = f"""
    <div style="border:2px solid red;padding:10px;margin:10px 0;border-radius:5px">
    <h2 style="color:red;margin-top:0">异动板块提醒</h2>
    <table border='1' cellpadding='5' cellspacing='0'>
      <tr><th>板块</th><th>信号类型</th><th>描述</th><th>数据来源</th><th>严重程度</th></tr>
      {anomaly_rows}
    </table>
    </div>"""

        # --- Sector table ---
        sector_rows = ""
        for s in sector_rankings:
            b = s.get("breakdown", {})
            sector_rows += f"""
        <tr>
          <td>{s['rank']}</td>
          <td><strong>{html.escape(s['name'])}</strong></td>
          <td><strong>{s['score']:.3f}</strong></td>
          <td>{b.get('momentum', '-'):.3f}</td>
          <td>{b.get('valuation', '-'):.3f}</td>
          <td>{b.get('macro', '-'):.3f}</td>
          <td>{b.get('fundamentals', '-'):.3f}</td>
        </tr>"""
        sectors_table = f"""
    <h2>一、板块扫描结果</h2>
    <p>权重方法: A(动量)×0.4 + B(估值)×0.3 + E(宏观)×0.2 + C(基本面)×0.1</p>
    <table border='1' cellpadding='5' cellspacing='0'>
      <tr><th>排名</th><th>板块</th><th>综合得分</th><th>动量(A)</th><th>估值(B)</th><th>宏观(E)</th><th>基本面(C)</th></tr>
      {sector_rows}
    </table>"""

        # --- Per-stock deep agent analysis ---
        stock_sections = ""
        for stock in deep_stocks:
            if stock.get("error"):
                stock_sections += f"""
        <div style="border:1px solid #ccc;padding:15px;margin:15px 0;background:#fff3f3">
        <h2>{html.escape(stock['ticker'])} — {html.escape(stock['sector'])}</h2>
        <p style="color:red">Error: {html.escape(stock['error'])}</p>
        </div>"""
                continue
            scores = stock.get("scores", {})
            rating_color = {
                "Buy": "green", "Overweight": "blue", "Hold": "gray",
                "Underweight": "orange", "Sell": "red"
            }.get(stock.get("rating", "Hold"), "gray")
            stock_sections += f"""
        <div style="border:1px solid #333;padding:15px;margin:15px 0;border-radius:8px">
        <h2 style="color:#1a1a1a;margin-bottom:5px">
          {html.escape(stock['ticker'])} — {html.escape(stock['sector'])}
        </h2>
        <p style="font-size:13px">
          综合得分: <strong>{stock.get('composite_score', 0):.3f}</strong> &nbsp;|&nbsp;
          评级: <strong style="color:{rating_color}">{html.escape(stock.get('rating', 'N/A'))}</strong>
        </p>

        <h3 style="color:#1565C0;border-left:4px solid #1565C0;padding-left:8px">动量/技术面 (Market Analyst)</h3>
        <div style="background:#f5f5f5;padding:10px;white-space:pre-wrap;font-size:13px">{html.escape(stock.get('market_report', 'No data'))}</div>

        <h3 style="color:#6A1B9A;border-left:4px solid #6A1B9A;padding-left:8px">情绪面 (Social Media Analyst)</h3>
        <div style="background:#f5f5f5;padding:10px;white-space:pre-wrap;font-size:13px">{html.escape(stock.get('sentiment_report', 'No data'))}</div>

        <h3 style="color:#E65100;border-left:4px solid #E65100;padding-left:8px">宏观/新闻面 (News Analyst)</h3>
        <div style="background:#f5f5f5;padding:10px;white-space:pre-wrap;font-size:13px">{html.escape(stock.get('news_report', 'No data'))}</div>

        <h3 style="color:#2E7D32;border-left:4px solid #2E7D32;padding-left:8px">基本面 (Fundamentals Analyst)</h3>
        <div style="background:#f5f5f5;padding:10px;white-space:pre-wrap;font-size:13px">{html.escape(stock.get('fundamentals_report', 'No data'))}</div>

        <h3 style="color:#0277BD;border-left:4px solid #0277BD;padding-left:8px">研究结论 (Research Manager)</h3>
        <div style="background:#e3f2fd;padding:10px;white-space:pre-wrap;font-size:13px">{html.escape(stock.get('investment_plan', 'No data'))}</div>

        <h3 style="color:#33691E;border-left:4px solid #33691E;padding-left:8px">交易计划 (Trader)</h3>
        <div style="background:#e8f5e9;padding:10px;white-space:pre-wrap;font-size:13px">{html.escape(stock.get('trader_plan', 'No data'))}</div>

        <h3 style="color:#BF360C;border-left:4px solid #BF360C;padding-left:8px">最终决策 (Portfolio Manager)</h3>
        <div style="background:#fff3e0;padding:10px;white-space:pre-wrap;font-size:13px;font-weight:bold">{html.escape(stock.get('final_decision', 'No data'))}</div>
        </div>"""

        # --- Portfolio positions ---
        pos_section = ""
        if portfolio_positions:
            pos_rows = ""
            total_value = 0
            for p in portfolio_positions:
                value = p.get("shares", 0) * p.get("entry_price", 0)
                total_value += value
                pos_rows += f"""
        <tr>
          <td>{html.escape(p.get('ticker', ''))}</td>
          <td>{p.get('shares', 0)}</td>
          <td>${p.get('entry_price', 0):.2f}</td>
          <td>${value:.2f}</td>
          <td>{html.escape(p.get('broker', ''))}</td>
        </tr>"""
            pos_section = f"""
    <h2 style="margin-top:30px">三、现有持仓</h2>
    <p>总持仓市值: <strong>${total_value:.2f}</strong></p>
    <table border='1' cellpadding='5' cellspacing='0'>
      <tr><th>股票</th><th>股数</th><th>买入价</th><th>市值</th><th>券商</th></tr>
      {pos_rows}
    </table>"""

        # --- Adjustments ---
        reduce_rows = "".join(
            f"<tr><td>{html.escape(a['ticker'])}</td><td>{a['current_shares']}</td>"
            f"<td>减至{a['recommended_shares']}股</td><td>{html.escape(a.get('reason', ''))}</td></tr>"
            for a in adjustments if a["action"] in ("REDUCE", "ADD")
        )
        new_rows = "".join(
            f"<tr><td>{html.escape(a['ticker'])}</td><td>建议新建仓{a['recommended_shares']}股</td>"
            f"<td>{html.escape(a.get('reason', ''))}</td></tr>"
            for a in adjustments if a["action"] == "NEW"
        )
        hold_rows = "".join(
            f"<tr><td>{html.escape(u['ticker'])}</td><td>{html.escape(u.get('reason', ''))}</td></tr>"
            for u in unchanged
        )
        adjustments_section = f"""
    <h2 style="margin-top:30px">四、持仓调整建议</h2>
    {('<h3>建议减仓</h3><table border="1" cellpadding="5" cellspacing="0"><tr><th>股票</th><th>当前持仓</th><th>建议</th><th>原因</th></tr>' + reduce_rows + '</table>' if reduce_rows else '<p>无减仓建议</p>')}
    {('<h3>新建仓机会</h3><table border="1" cellpadding="5" cellspacing="0"><tr><th>股票</th><th>建议</th><th>原因</th></tr>' + new_rows + '</table>' if new_rows else '')}
    {('<h3>持仓不变</h3><table border="1" cellpadding="5" cellspacing="0"><tr><th>股票</th><th>原因</th></tr>' + hold_rows + '</table>' if hold_rows else '')}"""

        body = f"""
    <div style="font-family:Arial,sans-serif;max-width:950px">
    <h1 style="color:#333">Daily Stock Screener & Agent Analysis</h1>
    <p><em>扫描日期: {scan_date} | 报告生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M')}</em></p>
    {anomaly_section}
    {sectors_table}
    <h2 style="margin-top:30px">二、Top 8 个股深度 Agent 分析</h2>
    <p>每只股票经过: Market Analyst → Social Media Analyst → News Analyst → Fundamentals Analyst → Research Manager → Trader → Portfolio Manager</p>
    {stock_sections}
    {pos_section}
    {adjustments_section}
    <p style="margin-top:20px"><em>Generated by TradingAgents Stock Screener | 权重: A×0.4 + B×0.3 + E×0.2 + C×0.1</em></p>
    </div>"""
        return EmailMessage(
            subject=f"[TradingAgents] Stock Screener — {scan_date}",
            body=body,
            to_email=self.recipient_email,
        )
        """Format weekly comprehensive report."""
        portfolio_value = report.get("portfolio_value", 0)
        gain_loss = report.get("gain_loss", 0)
        positions = report.get("positions", [])
        recommendations = report.get("recommendations", [])

        # Determine color for gain/loss
        gl_color = 'green' if gain_loss >= 0 else 'red'
        gl_formatted = _escape_html(_fmt_price(gain_loss))

        # Build table rows
        rows = []
        for p in positions:
            ticker = _escape_html(p['ticker'])
            shares = _escape_html(str(p['shares']))
            entry = _escape_html(_fmt_price(p['entry_price']))
            current = _escape_html(p.get('current_price', 'N/A'))
            pnl = p.get('pnl', 0)
            pnl_color = 'green' if pnl >= 0 else 'red'
            pnl_formatted = _escape_html(_fmt_pnl(pnl))
            rec = _escape_html(p.get('recommendation', 'Hold'))
            rows.append(f"<tr><td>{ticker}</td><td>{shares}</td><td>{entry}</td><td>{current}</td><td style='color: {pnl_color}'>{pnl_formatted}</td><td>{rec}</td></tr>")

        body = f"""
        <h2>Weekly Portfolio Report</h2>

        <h3>Portfolio Summary</h3>
        <p>Total Value: <strong>{_escape_html(_fmt_price(portfolio_value))}</strong></p>
        <p>Gain/Loss: <strong style="color: {gl_color}">{gl_formatted}</strong></p>

        <h3>Current Positions</h3>
        <table border="1" cellpadding="5" cellspacing="0">
            <tr><th>Ticker</th><th>Shares</th><th>Entry</th><th>Current</th><th>P/L</th><th>Action</th></tr>
            {''.join(rows)}
        </table>

        <h3>Recommendations</h3>
        <ul>
            {''.join(f"<li>{_escape_html(r)}</li>" for r in recommendations)}
        </ul>

        <h3>Market Outlook</h3>
        <p>{_escape_html(report.get('market_outlook', 'No data available'))}</p>

        <p><em>Generated by TradingAgents - Weekly Analysis</em></p>
        """

        return EmailMessage(
            subject=f"Weekly Portfolio Report - {_escape_html(report.get('week', 'This Week'))}",
            body=body,
            to_email=self.recipient_email
        )