"""Gmail Pusher - sends analysis reports via Gmail."""

import html
import smtplib
import os
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dataclasses import dataclass
from typing import Optional


def _escape_html(text):
    """Escape HTML characters to prevent injection."""
    if isinstance(text, str):
        return html.escape(text)
    return str(text)


def _fmt_price(price):
    """Format price for display in email."""
    return f"${price:.2f}"


def _fmt_pnl(pnl):
    """Format P/L for display in email."""
    return f"${pnl:.2f}"


@dataclass
class EmailMessage:
    """Email message structure."""
    subject: str
    body: str
    to_email: str
    cc_email: Optional[str] = None


class GmailPusher:
    """Sends emails via Gmail SMTP."""

    def __init__(self, sender_email: str, recipient_email: str,
                 smtp_host: str = "smtp.gmail.com",
                 smtp_port: int = 587):
        self.sender_email = sender_email
        self.recipient_email = recipient_email
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port

    def _get_credentials(self) -> tuple[str, str]:
        """Get SMTP credentials from environment."""
        email_user = os.getenv("GMAIL_EMAIL")
        email_pass = os.getenv("GMAIL_APP_PASSWORD")
        if not email_user or not email_pass:
            raise ValueError(
                "Gmail credentials not set. Please set GMAIL_EMAIL and GMAIL_APP_PASSWORD environment variables."
            )
        return email_user, email_pass

    def send_email(self, message: EmailMessage) -> bool:
        """Send an email via Gmail SMTP."""
        try:
            email_user, email_pass = self._get_credentials()

            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = message.to_email
            if message.cc_email:
                msg['Cc'] = message.cc_email
            msg['Subject'] = message.subject

            msg.attach(MIMEText(message.body, 'html'))

            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(email_user, email_pass)
                server.send_message(msg)

            return True
        except smtplib.SMTPException as e:
            print(f"Failed to send email: {e}")
            return False

    def send_with_retry(self, message: EmailMessage, max_retries: int = 3) -> bool:
        """Send email with retry logic."""
        delays = [5, 15, 60]  # minutes
        for attempt in range(max_retries):
            if self.send_email(message):
                return True
            if attempt < max_retries - 1:
                wait_time = delays[attempt] * 60
                print(f"Retry {attempt + 1}/{max_retries} in {delays[attempt]} minutes...")
                time.sleep(wait_time)
        return False

    def format_premarket_briefing(self, report: dict) -> EmailMessage:
        """Format premarket briefing email."""
        positions = report.get("positions", [])
        sentiment = report.get("sentiment", "neutral")
        events = report.get("events", [])

        # Build table rows
        rows = []
        for p in positions:
            ticker = _escape_html(p['ticker'])
            shares = _escape_html(str(p['shares']))
            price = _escape_html(_fmt_price(p['entry_price']))
            rows.append(f"<tr><td>{ticker}</td><td>{shares}</td><td>{price}</td></tr>")

        body = f"""
        <h2>Pre-market Briefing</h2>
        <h3>Portfolio Positions</h3>
        <table border="1" cellpadding="5" cellspacing="0">
            <tr><th>Ticker</th><th>Shares</th><th>Entry Price</th></tr>
            {''.join(rows)}
        </table>

        <h3>Market Sentiment</h3>
        <p>{_escape_html(sentiment.upper())}</p>

        <h3>Key Events Today</h3>
        <ul>
            {''.join(f"<li>{_escape_html(e)}</li>" for e in events)}
        </ul>

        <p><em>Generated by TradingAgents</em></p>
        """

        return EmailMessage(
            subject=f"Pre-market Briefing - {_escape_html(report.get('date', 'Today'))}",
            body=body,
            to_email=self.recipient_email
        )

    def format_afterhours_report(self, report: dict) -> EmailMessage:
        """Format after-hours report email."""
        positions = report.get("positions", [])
        analysis = report.get("analysis", "")

        # Build table rows
        rows = []
        for p in positions:
            ticker = _escape_html(p['ticker'])
            shares = _escape_html(str(p['shares']))
            current = _escape_html(p.get('current_price', 'N/A'))
            action = _escape_html(p.get('action', 'Hold'))
            rows.append(f"<tr><td>{ticker}</td><td>{shares}</td><td>{current}</td><td>{action}</td></tr>")

        body = f"""
        <h2>After-hours Report</h2>
        <h3>Portfolio Performance</h3>
        <table border="1" cellpadding="5" cellspacing="0">
            <tr><th>Ticker</th><th>Shares</th><th>Current/Pivot</th><th>Action</th></tr>
            {''.join(rows)}
        </table>

        <h3>Analysis Summary</h3>
        <p>{_escape_html(analysis)}</p>

        <p><em>Generated by TradingAgents</em></p>
        """

        return EmailMessage(
            subject=f"After-hours Report - {_escape_html(report.get('date', 'Today'))}",
            body=body,
            to_email=self.recipient_email
        )

    def format_weekly_report(self, report: dict) -> EmailMessage:
        """Format weekly comprehensive report."""
        portfolio_value = report.get("portfolio_value", 0)
        gain_loss = report.get("gain_loss", 0)
        positions = report.get("positions", [])
        recommendations = report.get("recommendations", [])

        # Determine color for gain/loss
        gl_color = 'green' if gain_loss >= 0 else 'red'
        gl_formatted = _escape_html(_fmt_price(gain_loss))

        # Build table rows
        rows = []
        for p in positions:
            ticker = _escape_html(p['ticker'])
            shares = _escape_html(str(p['shares']))
            entry = _escape_html(_fmt_price(p['entry_price']))
            current = _escape_html(p.get('current_price', 'N/A'))
            pnl = p.get('pnl', 0)
            pnl_color = 'green' if pnl >= 0 else 'red'
            pnl_formatted = _escape_html(_fmt_pnl(pnl))
            rec = _escape_html(p.get('recommendation', 'Hold'))
            rows.append(f"<tr><td>{ticker}</td><td>{shares}</td><td>{entry}</td><td>{current}</td><td style='color: {pnl_color}'>{pnl_formatted}</td><td>{rec}</td></tr>")

        body = f"""
        <h2>Weekly Portfolio Report</h2>

        <h3>Portfolio Summary</h3>
        <p>Total Value: <strong>{_escape_html(_fmt_price(portfolio_value))}</strong></p>
        <p>Gain/Loss: <strong style="color: {gl_color}">{gl_formatted}</strong></p>

        <h3>Current Positions</h3>
        <table border="1" cellpadding="5" cellspacing="0">
            <tr><th>Ticker</th><th>Shares</th><th>Entry</th><th>Current</th><th>P/L</th><th>Action</th></tr>
            {''.join(rows)}
        </table>

        <h3>Recommendations</h3>
        <ul>
            {''.join(f"<li>{_escape_html(r)}</li>" for r in recommendations)}
        </ul>

        <h3>Market Outlook</h3>
        <p>{_escape_html(report.get('market_outlook', 'No data available'))}</p>

        <p><em>Generated by TradingAgents - Weekly Analysis</em></p>
        """

        return EmailMessage(
            subject=f"Weekly Portfolio Report - {_escape_html(report.get('week', 'This Week'))}",
            body=body,
            to_email=self.recipient_email
        )